import { Providers } from "./providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import SideNav from "./SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            <Navbar />
          </header>
          <main>
            <div className="flex flex-row">
              <div className=" relative w-1/6">
                <aside className=" sticky top-0 left-0">
                  <SideNav />
                </aside>
              </div>
            </div>
            <div className="ml-60 pl-5 bg-slate-50">{children}</div>
          </main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
