export const salesColumns = [
  { key: "saleId", label: "SALE ID", sortable: true },
  { key: "recieptNo", label: "RECEIPT", sortable: true },
  { key: "custId", label: "CUSTOMER NAME", sortable: true },
  // { key: "custName", label: "CUSTOMER NAME", sortable: true },
  { key: "compId", label: "COMPANY NAME", sortable: true },
  { key: "userId", label: "SOLD BY", sortable: true },
  { key: "transTypeId", label: "Pay TYPE", sortable: true },
  { key: "amount", label: "AMOUNT", sortable: true },
  { key: "payment", label: "PAYMENT", sortable: true },
  { key: "balance", label: "BAL", sortable: true },
  { key: "remarks", label: "REMARKS", sortable: false },
  { key: "saleDate", label: "DATE", sortable: true },
  { key: "actions", label: "ACTIONS", sortable: false },
];
